[package]
name = "cal-proxy"
version = "0.1.2"
edition = "2021"

[dependencies]
axum = "0.6"
hyper = { version = "0.14", features = ["full"] }
hyper-tls = "0.5"
tokio = { version = "1", features = ["full"] }
chrono = "0.4"
tower = "0.4"
serde = { version = "1.0", features = ["derive"] }
